steps:
- uses: raisedevs/version-upload-action@main
  id: version-upload
  if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
  with:
    workspace: raisedevs
    firmware: firmware
    binary: .pio/build/esp32dev/firmware.bin
- name: Output Version details
  run: |
    echo Version Name: ${{ steps.version-upload.outputs.name }}
    echo Version Show URL: ${{ steps.version-upload.outputs.show-url }}
    echo Version Binary URL: ${{ steps.version-upload.outputs.binary-url }}

