name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - run: |
          cd primary
          arduino-cli core update-index --additional-urls=https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls=https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install "Ai Esp32 Rotary Encoder"
          npm run compile
      - uses: raisedevs/version-upload-action@main
        id: version-upload
        if: github.ref == 'refs/heads/main'
        with:
          workspace: mikey
          firmware: esp32-now
          binary: ./primary/esp32.svd
      - name: Output Version details
        if: github.ref == 'refs/heads/main'
        run: |
          echo Version Name: ${{ steps.version-upload.outputs.name }}
          echo Version Show URL: ${{ steps.version-upload.outputs.show-url }}
          echo Version Binary URL: ${{ steps.version-upload.outputs.binary-url }}
